# Generated by Django 5.2.3 on 2026-02-24 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_snippet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Сниппет', 'verbose_name_plural': 'Сниппеты'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='created_at',
            new_name='creation_date',
        ),
    ]
