# Generated by Django 5.2.3 on 2026-02-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('', 'Выберите язык...'), ('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('cpp', 'C++'), ('c', 'C'), ('csharp', 'C#'), ('php', 'PHP'), ('ruby', 'Ruby'), ('go', 'Go'), ('rust', 'Rust'), ('swift', 'Swift'), ('kotlin', 'Kotlin'), ('typescript', 'TypeScript'), ('sql', 'SQL'), ('bash', 'Bash/Shell'), ('html', 'HTML'), ('css', 'CSS'), ('other', 'Другой')], default='python', max_length=30, verbose_name='Язык'),
        ),
    ]
